Now, when "make" fails to certify a book, it prints:
   1. The **CERTIFICATION FAILED** line, as usual;
   2. The last 300 lines of the .out file, nicely indented; and
   3. The **CERTIFICATION FAILED** line, again, so you can see which
      file had the problem without scrolling back up.

To try this out, just add an "i-am-here" to any random book and try to certify
it.

I think this is convenient in the course of regular book development, because
it often lets me see why a book is failing without needing to open the .out
file or manually load the book.

It may also be very useful in automated regression scripts which send you an
email when they fail.  That is, often the last 300 lines are sufficient to see
why a book is failing, so as the recipient of such an email may not need to log
into a remote machine and look at a .out file.

diff --git a/books/Makefile-generic b/books/Makefile-generic
--- a/books/Makefile-generic
+++ b/books/Makefile-generic
@@ -149,7 +149,14 @@ BOOKS_LISP    = $(patsubst %, %.lisp,    $(BOOKS))
 	fi	
 	@($(ACL2) < workxxx.$(*F) 2>&1) > $*.out
 	@rm -f workxxx.$(*F)
-	@((test -f $<) && (ls -al $*.cert)) || (echo "**CERTIFICATION FAILED** for `pwd`/$*.lisp" ; exit 1)
+	@((test -f $<) && (ls -al $*.cert)) || \
+            (echo "**CERTIFICATION FAILED** for `pwd`/$*.lisp" ;\
+	     echo "" ;\
+	     tail -300 $*.out | sed 's/^/   | /' ;\
+	     echo "" ;\
+	     echo "" ;\
+	     echo "**CERTIFICATION FAILED** for `pwd`/$*.lisp" ;\
+             exit 1)
 # The following code can replace the line just above.  However, it is a bit
 # complicated by our having seen sh on Sun/Solaris 5.9 fail to recognize -nt,
 # which is this code uses csh instead of sh if possible.  At any rate, the test
