Updated 3.4 to trunk rev 236.  Compatibility mods: Excluded broken books in defsort/Makefile, str/Makefile, and modified str/top.lisp, str/abbrevs.lisp.

diff --git a/books/branches/3.4/Makefile-generic b/books/branches/3.4/Makefile-generic
--- a/books/branches/3.4/Makefile-generic
+++ b/books/branches/3.4/Makefile-generic
@@ -94,17 +94,18 @@ BOOKS := $(patsubst %.lisp, %, $(wildcard *.lisp))
 # so that BOOKS can be redefined after including this file in another makefile
 # and the variables below will automatically be updated accordingly.
 
-BOOKS_CERT   = $(patsubst %, %.cert, $(BOOKS))
-BOOKS_FASL   = $(patsubst %, %.fasl, $(BOOKS))
-BOOKS_FAS   = $(patsubst %, %.fas, $(BOOKS))
-BOOKS_SPARCF = $(patsubst %, %.sparcf, $(BOOKS))
-BOOKS_UFSL = $(patsubst %, %.ufsl, $(BOOKS))
-BOOKS_DFSL = $(patsubst %, %.dfsl, $(BOOKS))
-BOOKS_D64FSL = $(patsubst %, %.d64fsl, $(BOOKS))
+BOOKS_CERT    = $(patsubst %, %.cert,    $(BOOKS))
+BOOKS_FASL    = $(patsubst %, %.fasl,    $(BOOKS))
+BOOKS_FAS     = $(patsubst %, %.fas,     $(BOOKS))
+BOOKS_SPARCF  = $(patsubst %, %.sparcf,  $(BOOKS))
+BOOKS_UFSL    = $(patsubst %, %.ufsl,    $(BOOKS))
+BOOKS_DFSL    = $(patsubst %, %.dfsl,    $(BOOKS))
+BOOKS_D64FSL  = $(patsubst %, %.d64fsl,  $(BOOKS))
 BOOKS_DX64FSL = $(patsubst %, %.dx64fsl, $(BOOKS))
 BOOKS_LX64FSL = $(patsubst %, %.lx64fsl, $(BOOKS))
-BOOKS_X86F = $(patsubst %, %.x86f, $(BOOKS))
-BOOKS_O      = $(patsubst %, %.o, $(BOOKS))
+BOOKS_X86F    = $(patsubst %, %.x86f,    $(BOOKS))
+BOOKS_O       = $(patsubst %, %.o,       $(BOOKS))
+BOOKS_LISP    = $(patsubst %, %.lisp,    $(BOOKS))
 
 #  This tells make to expect `suffix rules' for these file suffixes.
 
@@ -148,7 +149,14 @@ BOOKS_O      = $(patsubst %, %.o, $(BOOKS))
 	fi	
 	@($(ACL2) < workxxx.$(*F) 2>&1) > $*.out
 	@rm -f workxxx.$(*F)
-	@((test -f $<) && (ls -al $*.cert)) || (echo "**CERTIFICATION FAILED** for `pwd`/$*.lisp" ; exit 1)
+	@((test -f $<) && (ls -al $*.cert)) || \
+            (echo "**CERTIFICATION FAILED** for `pwd`/$*.lisp" ;\
+	     echo "" ;\
+	     tail -300 $*.out | sed 's/^/   | /' ;\
+	     echo "" ;\
+	     echo "" ;\
+	     echo "**CERTIFICATION FAILED** for `pwd`/$*.lisp" ;\
+             exit 1)
 # The following code can replace the line just above.  However, it is a bit
 # complicated by our having seen sh on Sun/Solaris 5.9 fail to recognize -nt,
 # which is this code uses csh instead of sh if possible.  At any rate, the test
@@ -266,6 +274,10 @@ lx64fsl:
 	@echo "Making $$PWD/$@"
 	echo '(acl2::value :q) (acl2::lp) (ld `((include-book "$(patsubst %.lx64fsl,%,$(@))" :load-compiled-file :comp :ttags :all))) (acl2::value :q) (acl2::exit-lisp)' | $(ACL2)
 
+.PHONY: nothing
+nothing:
+	@echo "There\'s a good reason to do this here."
+
 # The dependencies rule prints make dependency commands to the screen.  The basic
 # strategy is to look for include-book commands, and to prefix appropriately
 # "$(ACL2_SYSTEM_BOOKS)" when :dir :system is specified.  Thus, if :dir :system is
@@ -287,9 +299,9 @@ lx64fsl:
 # generate dependency lines.
 
 # Grep commands to rule out :dir :system:
-ACL2_NON_DIR            = egrep -i -v ':dir[ \t]*:system'
+ACL2_NON_DIR            = egrep -i -v ':dir'
 
-# Grep commands for include-book and ld forms withOUT :dir :system:
+# Grep commands for include-book and ld forms withOUT :dir:
 ACL2_EGREP_CMD          = egrep -i '^[^;]*include-book[ \t]*\".*\"' $$book.lisp | $(ACL2_NON_DIR)
 ACL2_EGREP_CMD_ACL2     = $(subst book.lisp,book.acl2,$(ACL2_EGREP_CMD))
 ACL2_EGREP_CMD_CERT     = $(subst $$book.lisp,cert.acl2,$(ACL2_EGREP_CMD))
@@ -334,6 +346,7 @@ dependencies:
 
 .PHONY: clean
 clean:
+	rm -f Makefile-deps
 	rm -f *.cert
 	rm -f *.h
 	rm -f *.c
@@ -361,3 +374,18 @@ clean:
 	rm -f *@expansion.lsp
 	rm -f temp-emacs-file.lsp
 	rm -f workxxx*
+
+ifdef FAST_DEPS_FOR_CLEAN
+# Note that Makefile-deps will be deleted by the clean target
+# immediately after the following code creates it.
+Makefile-deps: 
+	@echo "# Skipping deps" > Makefile-deps
+else
+# The argument --no-print-directory below avoids lines like:
+# make[3]: Leaving directory `/v/filer4b/v11q001/acl2/devel/v3-5-alpha-aug31/books/bdd'
+Makefile-deps: $(BOOKS_LISP) $(wildcard *.acl2)
+	@echo "Updating dependencies in `pwd`"
+	@rm -f Makefile-deps
+	@echo "# This file is automatically generated; do not hand edit." > Makefile-deps
+	+@make --no-print-directory -s dependencies >> Makefile-deps
+endif
